import type { BrandPalette } from '../design-system/designTokens';

export type TemplateId =
  | 'cover'
  | 'text'
  | 'data'
  | 'list'
  | 'quote'
  | 'comparison'
  | 'cta'
  | 'news'
  | 'story'
  | 'closing';

export type SlideTheme = 'dark' | 'light' | 'accent';

/**
 * Slide content, independent of layout.
 * The system never rewrites these fields — it only positions them.
 */
export interface SlideContent {
  eyebrow?: string;
  headline?: string;
  body?: string;
  number?: string;
  items?: string[];
  quote?: string;
  author?: string;
  source?: string;
  cta?: string;
  handle?: string;
  date?: string;
  name?: string;
  tag?: string;
  leftTitle?: string;
  leftBody?: string;
  rightTitle?: string;
  rightBody?: string;
}

export type ContentKey = keyof SlideContent;

export type ElementType = 'text' | 'shape' | 'image' | 'logo' | 'tag';

export type ShapeKind = 'rect' | 'ellipse' | 'line' | 'arrow' | 'arch' | 'archOutline';

export type ImageMask = 'rect' | 'arch' | 'circle';

export type LogoVariant = 'horizontal' | 'horizontalNegative' | 'symbol' | 'symbolNegative' | 'compact' | 'compactNegative';

export interface ShadowStyle {
  enabled: boolean;
  color: string;
  blur: number;
  offsetX: number;
  offsetY: number;
  opacity: number;
}

interface BaseElement {
  id: string;
  type: ElementType;
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  opacity: number;
  locked?: boolean;
  hidden?: boolean;
  /** Created by the template (regenerated by "Organizar layout") */
  templateOwned?: boolean;
  /** Semantic role, used by the auto-layout */
  role?: string;
  shadow?: ShadowStyle;
}

export interface TextElement extends BaseElement {
  type: 'text';
  text: string;
  /** Links the text to a SlideContent field (two-way editing) */
  bind?: ContentKey;
  /** Index into items[] when bind === 'items' */
  bindIndex?: number;
  fontSize: number;
  fontWeight: number;
  lineHeight: number;
  /** In em */
  letterSpacing: number;
  align: 'left' | 'center' | 'right';
  color: string;
  /** Color of words marked with *asterisks* */
  highlightColor: string;
  uppercase?: boolean;
  /** Text box with a background */
  background?: string;
  padding?: number;
  cornerRadius?: number;
}

export interface ShapeElement extends BaseElement {
  type: 'shape';
  shape: ShapeKind;
  fill: string;
  stroke: string;
  strokeWidth: number;
  cornerRadius: number;
}

export interface ImageElement extends BaseElement {
  type: 'image';
  assetId: string;
  mask: ImageMask;
  cornerRadius: number;
  /** Zoom of the image inside the frame (1 = cover) */
  zoom: number;
  /** Offset of the image inside the frame (-1..1) */
  offsetX: number;
  offsetY: number;
  /** Brand treatment */
  treatment: 'none' | 'mono' | 'greenTint' | 'duotone';
  stroke: string;
  strokeWidth: number;
}

export interface LogoElement extends BaseElement {
  type: 'logo';
  variant: LogoVariant;
}

export interface TagElement extends BaseElement {
  type: 'tag';
  text: string;
  bind?: ContentKey;
  fill: string;
  stroke: string;
  strokeWidth: number;
  color: string;
  fontSize: number;
  fontWeight: number;
  letterSpacing: number;
  cornerRadius: number;
  paddingX: number;
  uppercase?: boolean;
}

export type CarouselElement = TextElement | ShapeElement | ImageElement | LogoElement | TagElement;

export interface Slide {
  id: string;
  name: string;
  template: TemplateId;
  theme: SlideTheme;
  content: SlideContent;
  /** Original text of the block, kept for reference */
  rawText?: string;
  background: string;
  elements: CarouselElement[];
}

export interface Asset {
  id: string;
  name: string;
  kind: 'photo' | 'logo' | 'icon' | 'graphic';
  /** data URL (persisted in IndexedDB) or path in /public */
  src: string;
  width: number;
  height: number;
  /** Brand logo slot */
  logoVariant?: LogoVariant;
}

export interface CarouselSettings {
  showHeader: boolean;
  showFooter: boolean;
  showCounter: boolean;
  handle: string;
  eyebrowDefault: string;
}

export interface Project {
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;
  slides: Slide[];
  palette: BrandPalette;
  settings: CarouselSettings;
  assets: Record<string, Asset>;
  /** Small thumbnail (data URL) for the dashboard */
  thumbnail?: string;
}

export interface ProjectMeta {
  id: string;
  name: string;
  updatedAt: number;
  slideCount: number;
  thumbnail?: string;
}

/** Slide detected by the parser (before creation) */
export interface ParsedSlide {
  index: number;
  rawText: string;
  content: SlideContent;
  suggested: TemplateId;
  reason: string;
}
